export const repo = {
  id: 268715709,
  node_id: "MDEwOlJlcG9zaXRvcnkyNjg3MTU3MDk=",
  name: "scripts",
  full_name: "inpyjamas/scripts",
  private: false,
  owner: {
    login: "inpyjamas",
    id: 61817025,
    node_id: "MDEyOk9yZ2FuaXphdGlvbjYxODE3MDI1",
    avatar_url: "https://avatars1.githubusercontent.com/u/61817025?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/inpyjamas",
    html_url: "https://github.com/inpyjamas",
    followers_url: "https://api.github.com/users/inpyjamas/followers",
    following_url:
      "https://api.github.com/users/inpyjamas/following{/other_user}",
    gists_url: "https://api.github.com/users/inpyjamas/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/inpyjamas/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/inpyjamas/subscriptions",
    organizations_url: "https://api.github.com/users/inpyjamas/orgs",
    repos_url: "https://api.github.com/users/inpyjamas/repos",
    events_url: "https://api.github.com/users/inpyjamas/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/inpyjamas/received_events",
    type: "Organization",
    site_admin: false,
  },
  html_url: "https://github.com/inpyjamas/scripts",
  description: null,
  fork: false,
  url: "https://api.github.com/repos/inpyjamas/scripts",
  forks_url: "https://api.github.com/repos/inpyjamas/scripts/forks",
  keys_url: "https://api.github.com/repos/inpyjamas/scripts/keys{/key_id}",
  collaborators_url:
    "https://api.github.com/repos/inpyjamas/scripts/collaborators{/collaborator}",
  teams_url: "https://api.github.com/repos/inpyjamas/scripts/teams",
  hooks_url: "https://api.github.com/repos/inpyjamas/scripts/hooks",
  issue_events_url:
    "https://api.github.com/repos/inpyjamas/scripts/issues/events{/number}",
  events_url: "https://api.github.com/repos/inpyjamas/scripts/events",
  assignees_url:
    "https://api.github.com/repos/inpyjamas/scripts/assignees{/user}",
  branches_url:
    "https://api.github.com/repos/inpyjamas/scripts/branches{/branch}",
  tags_url: "https://api.github.com/repos/inpyjamas/scripts/tags",
  blobs_url: "https://api.github.com/repos/inpyjamas/scripts/git/blobs{/sha}",
  git_tags_url: "https://api.github.com/repos/inpyjamas/scripts/git/tags{/sha}",
  git_refs_url: "https://api.github.com/repos/inpyjamas/scripts/git/refs{/sha}",
  trees_url: "https://api.github.com/repos/inpyjamas/scripts/git/trees{/sha}",
  statuses_url: "https://api.github.com/repos/inpyjamas/scripts/statuses/{sha}",
  languages_url: "https://api.github.com/repos/inpyjamas/scripts/languages",
  stargazers_url: "https://api.github.com/repos/inpyjamas/scripts/stargazers",
  contributors_url:
    "https://api.github.com/repos/inpyjamas/scripts/contributors",
  subscribers_url: "https://api.github.com/repos/inpyjamas/scripts/subscribers",
  subscription_url:
    "https://api.github.com/repos/inpyjamas/scripts/subscription",
  commits_url: "https://api.github.com/repos/inpyjamas/scripts/commits{/sha}",
  git_commits_url:
    "https://api.github.com/repos/inpyjamas/scripts/git/commits{/sha}",
  comments_url:
    "https://api.github.com/repos/inpyjamas/scripts/comments{/number}",
  issue_comment_url:
    "https://api.github.com/repos/inpyjamas/scripts/issues/comments{/number}",
  contents_url:
    "https://api.github.com/repos/inpyjamas/scripts/contents/{+path}",
  compare_url:
    "https://api.github.com/repos/inpyjamas/scripts/compare/{base}...{head}",
  merges_url: "https://api.github.com/repos/inpyjamas/scripts/merges",
  archive_url:
    "https://api.github.com/repos/inpyjamas/scripts/{archive_format}{/ref}",
  downloads_url: "https://api.github.com/repos/inpyjamas/scripts/downloads",
  issues_url: "https://api.github.com/repos/inpyjamas/scripts/issues{/number}",
  pulls_url: "https://api.github.com/repos/inpyjamas/scripts/pulls{/number}",
  milestones_url:
    "https://api.github.com/repos/inpyjamas/scripts/milestones{/number}",
  notifications_url:
    "https://api.github.com/repos/inpyjamas/scripts/notifications{?since,all,participating}",
  labels_url: "https://api.github.com/repos/inpyjamas/scripts/labels{/name}",
  releases_url: "https://api.github.com/repos/inpyjamas/scripts/releases{/id}",
  deployments_url: "https://api.github.com/repos/inpyjamas/scripts/deployments",
  created_at: "2020-06-02T06:09:04Z",
  updated_at: "2020-08-07T06:38:33Z",
  pushed_at: "2020-08-07T06:38:35Z",
  git_url: "git://github.com/inpyjamas/scripts.git",
  ssh_url: "git@github.com:inpyjamas/scripts.git",
  clone_url: "https://github.com/inpyjamas/scripts.git",
  svn_url: "https://github.com/inpyjamas/scripts",
  homepage: null,
  size: 502,
  stargazers_count: 1,
  watchers_count: 1,
  language: "TypeScript",
  has_issues: true,
  has_projects: true,
  has_downloads: true,
  has_wiki: true,
  has_pages: false,
  forks_count: 0,
  mirror_url: null,
  archived: false,
  disabled: false,
  open_issues_count: 4,
  license: {
    key: "mit",
    name: "MIT License",
    spdx_id: "MIT",
    url: "https://api.github.com/licenses/mit",
    node_id: "MDc6TGljZW5zZTEz",
  },
  forks: 0,
  open_issues: 4,
  watchers: 1,
  default_branch: "master",
  permissions: { admin: true, push: true, pull: true },
};
